name: Scrape LOGS Report

on:
  workflow_dispatch: {}
  schedule:
    - cron: "30 */8 * * *"  # every 8 hours (UTC)

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install --with-deps chromium

      - name: Run scraper
        env:
          LOGS_PAGE_URL: https://www.logs.com/mo-sales-report.html
          OUT_PATH: dashboard.json
        run: python scraper.py

      - name: Commit & push if changed
        if: success()
        run: |
          set -e
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add dashboard.json
            git commit -m "chore: update dashboard.json [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi

      - name: Upload debug artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: artifacts/
          if-no-files-found: ignore
